
FUNCTION create_contact_relationship (
    p_person_id             NUMBER DEFAULT NULL,
        -------
                    p_validate              VARCHAR2 DEFAULT 'TRUE',
    p_date_start            DATE DEFAULT SYSDATE,
    p_start_date            DATE DEFAULT SYSDATE,
    p_c_person_id           NUMBER DEFAULT NULL,
    p_contact_person_id     NUMBER DEFAULT NULL,
    p_title                 VARCHAR2 DEFAULT NULL,
    p_contact_type          VARCHAR2 DEFAULT NULL,
    p_primary_contact_flag  VARCHAR2 DEFAULT 'N',
    p_cont_attribute16      VARCHAR2 DEFAULT NULL,
    p_last_name             VARCHAR2 DEFAULT NULL,
    p_sex                   VARCHAR2 DEFAULT NULL,
    p_person_type_id        NUMBER DEFAULT 1125,
    p_date_of_birth         DATE DEFAULT NULL,
    p_first_name            VARCHAR2 DEFAULT NULL,
    p_personal_flag         VARCHAR2 DEFAULT 'N'
) RETURN CLOB;

FUNCTION update_contact_relationship(
    p_person_id                 NUMBER DEFAULT NULL,
    p_validate                  VARCHAR2 DEFAULT 'TRUE',
    p_effective_date            DATE DEFAULT SYSDATE,
    p_contact_relationship_id   NUMBER DEFAULT NULL,
    p_contact_type              VARCHAR2 DEFAULT NULL,
    p_primary_contact_flag      VARCHAR2 DEFAULT 'N',
    P_PERSONAL_FLAG             VARCHAR2 DEFAULT 'N',
    p_object_version_number     IN NUMBER
)RETURN CLOB;

FUNCTION delete_contact_relationship(
    p_person_id                 NUMBER DEFAULT NULL,
    p_validate                          IN VARCHAR2 DEFAULT 'TRUE',
    p_contact_relationship_id           IN NUMBER DEFAULT NULL,
    p_delete_other                      IN VARCHAR2 DEFAULT 'N',  
    p_object_version_number             IN NUMBER DEFAULT 1
)RETURN CLOB;

FUNCTION create_phone (
    p_person_id              NUMBER DEFAULT NULL,
    p_validate               IN  VARCHAR2 DEFAULT 'TRUE',
    p_date_from              IN  DATE DEFAULT SYSDATE,
    p_date_to                IN  DATE DEFAULT NULL,
    p_phone_type             IN  VARCHAR2,
    p_phone_number           IN  VARCHAR2,
    p_parent_id              IN  NUMBER DEFAULT NULL,
    p_parent_table           IN  VARCHAR2 DEFAULT NULL,
    p_attribute_category     IN  VARCHAR2 DEFAULT NULL,
    p_effective_date         IN  DATE DEFAULT SYSDATE,
    p_party_id               IN  NUMBER DEFAULT NULL,
    p_validity               IN  VARCHAR2 DEFAULT NULL
) RETURN CLOB;    

FUNCTION update_phone (
    p_person_id              NUMBER DEFAULT NULL,
    p_validate               IN  VARCHAR2 DEFAULT 'TRUE',
    p_phone_id               IN  NUMBER,
    p_date_from              IN  DATE DEFAULT SYSDATE,
    p_phone_type             IN  VARCHAR2,
    p_phone_number           IN  VARCHAR2,
    p_attribute_category     IN  VARCHAR2 DEFAULT NULL,
    p_effective_date         IN  DATE DEFAULT SYSDATE,
    p_party_id               IN  NUMBER DEFAULT NULL,
    p_validity               IN  VARCHAR2 DEFAULT NULL,
    p_object_version_number  IN  NUMBER
) RETURN CLOB;

FUNCTION delete_phone (
    p_person_id              NUMBER DEFAULT NULL,
    p_validate               IN  VARCHAR2 DEFAULT 'TRUE',
    p_phone_id               IN  NUMBER,
    p_object_version_number  IN  NUMBER
) RETURN CLOB;

FUNCTION create_person_address (
    p_person_id                NUMBER DEFAULT NULL,
    p_validate                 IN  VARCHAR2 DEFAULT 'TRUE',
    p_effective_date           IN  DATE,
    p_pradd_ovlapval_override  IN  BOOLEAN DEFAULT false,
    p_validate_county          IN  BOOLEAN DEFAULT true,
    p_primary_flag             IN  VARCHAR2,
    p_style                    IN  VARCHAR2,
    p_date_from                IN  DATE,
    p_date_to                  IN  DATE DEFAULT NULL,
    p_address_type             IN  VARCHAR2 DEFAULT NULL,
    p_comments                 IN  CLOB DEFAULT NULL,
    p_address_line1            IN  VARCHAR2 DEFAULT NULL,
    p_address_line2            IN  VARCHAR2 DEFAULT NULL,
    p_address_line3            IN  VARCHAR2 DEFAULT NULL,
    p_town_or_city             IN  VARCHAR2 DEFAULT NULL,
    p_region_1                 IN  VARCHAR2 DEFAULT NULL,
    p_region_2                 IN  VARCHAR2 DEFAULT NULL,
    p_region_3                 IN  VARCHAR2 DEFAULT NULL,
    p_postal_code              IN  VARCHAR2 DEFAULT NULL,
    p_country                  IN  VARCHAR2 DEFAULT NULL,
    p_telephone_number_1       IN  VARCHAR2 DEFAULT NULL,
    p_telephone_number_2       IN  VARCHAR2 DEFAULT NULL,
    p_telephone_number_3       IN  VARCHAR2 DEFAULT NULL,
    p_addr_attribute_category  IN  VARCHAR2 DEFAULT NULL,
    p_add_information13        IN  VARCHAR2 DEFAULT NULL,
    p_add_information14        IN  VARCHAR2 DEFAULT NULL,
    p_party_id                 IN  NUMBER DEFAULT NULL
) RETURN CLOB;

FUNCTION delete_person_address (
    p_person_id                NUMBER DEFAULT NULL,
    p_validate                 IN  VARCHAR2 DEFAULT 'TRUE',
    p_address_id               IN  NUMBER

) RETURN CLOB;

FUNCTION update_person_address (
    p_person_id                NUMBER DEFAULT NULL,
    p_validate                 IN  VARCHAR2 DEFAULT 'TRUE',
    p_effective_date           IN  DATE DEFAULT SYSDATE,
    p_validate_county          IN  BOOLEAN DEFAULT true,
    p_address_id               IN  NUMBER,
    p_date_from                IN  DATE DEFAULT NULL,
    p_date_to                  IN  DATE DEFAULT NULL,
    p_primary_flag             IN  VARCHAR2,
    p_address_type             IN  VARCHAR2 DEFAULT NULL,
    p_comments                 IN  CLOB DEFAULT NULL,
    p_address_line1            IN  VARCHAR2 DEFAULT NULL,
    p_address_line2            IN  VARCHAR2 DEFAULT NULL,
    p_address_line3            IN  VARCHAR2 DEFAULT NULL,
    p_town_or_city             IN  VARCHAR2 DEFAULT NULL,
    p_region_1                 IN  VARCHAR2 DEFAULT NULL,
    p_region_2                 IN  VARCHAR2 DEFAULT NULL,
    p_region_3                 IN  VARCHAR2 DEFAULT NULL,
    p_postal_code              IN  VARCHAR2 DEFAULT NULL,
    p_country                  IN  VARCHAR2 DEFAULT NULL,
    p_telephone_number_1       IN  VARCHAR2 DEFAULT NULL,
    p_telephone_number_2       IN  VARCHAR2 DEFAULT NULL,
    p_telephone_number_3       IN  VARCHAR2 DEFAULT NULL,
    p_addr_attribute_category  IN  VARCHAR2 DEFAULT NULL,
    p_add_information13        IN  VARCHAR2 DEFAULT NULL,
    p_add_information14        IN  VARCHAR2 DEFAULT NULL,
    p_party_id                 IN  NUMBER DEFAULT NULL
) RETURN CLOB;


FUNCTION create_sa_contact_person (
    p_person_id                     NUMBER DEFAULT NULL,
    p_validate                      IN  VARCHAR2 DEFAULT 'TRUE',
    p_start_date                    IN  DATE DEFAULT SYSDATE,
    p_business_group_id             IN  NUMBER DEFAULT NULL,
    p_person_type_id                IN  NUMBER DEFAULT NULL,
    p_family_name                   IN  VARCHAR2,
    p_sex                           IN  VARCHAR2,
    p_comments                      IN  VARCHAR2 DEFAULT NULL,
    p_date_employee_data_verified   IN  DATE DEFAULT NULL,
    p_date_of_birth                 IN  DATE DEFAULT NULL,
    p_email_address                 IN  VARCHAR2 DEFAULT NULL,
    p_expense_check_send_to_addres  IN  VARCHAR2 DEFAULT NULL,
    p_first_name                    IN  VARCHAR2 DEFAULT NULL,
    p_known_as                      IN  VARCHAR2 DEFAULT NULL,
    p_marital_status                IN  VARCHAR2 DEFAULT NULL,
    p_nationality                   IN  VARCHAR2 DEFAULT NULL,
    p_national_identifier           IN  VARCHAR2 DEFAULT NULL,
    p_previous_last_name            IN  VARCHAR2 DEFAULT NULL,
    p_registered_disabled_flag      IN  VARCHAR2 DEFAULT NULL,
    p_title                         IN  VARCHAR2 DEFAULT NULL,
    p_vendor_id                     IN  NUMBER DEFAULT NULL,
    p_work_telephone                IN  VARCHAR2 DEFAULT NULL,
    p_attribute_category            IN  VARCHAR2 DEFAULT NULL,
    p_father_name                   IN  VARCHAR2 DEFAULT NULL,
    p_grandfather_name              IN  VARCHAR2 DEFAULT NULL,
    p_alt_first_name                IN  VARCHAR2 DEFAULT NULL,
    p_alt_father_name               IN  VARCHAR2 DEFAULT NULL,
    p_alt_grandfather_name          IN  VARCHAR2 DEFAULT NULL,
    p_alt_family_name               IN  VARCHAR2 DEFAULT NULL,
    p_religion                      IN  VARCHAR2 DEFAULT NULL,
    p_hijrah_birth_date             IN  VARCHAR2 DEFAULT NULL,
    p_education_level               IN  VARCHAR2 DEFAULT NULL,
    p_correspondence_language       IN  VARCHAR2 DEFAULT NULL,
    p_honors                        IN  VARCHAR2 DEFAULT NULL,
    p_benefit_group_id              IN  NUMBER DEFAULT NULL,
    p_on_military_service           IN  VARCHAR2 DEFAULT NULL,
    p_student_status                IN  VARCHAR2 DEFAULT NULL,
    p_uses_tobacco_flag             IN  VARCHAR2 DEFAULT NULL,
    p_coord_ben_no_cvg_flag         IN  VARCHAR2 DEFAULT NULL,
    p_town_of_birth                 IN  VARCHAR2 DEFAULT NULL,
    p_region_of_birth               IN  VARCHAR2 DEFAULT NULL,
    p_country_of_birth              IN  VARCHAR2 DEFAULT NULL,
    p_global_person_id              IN  VARCHAR2 DEFAULT NULL,
    p_contact_type                  IN VARCHAR2 DEFAULT NULL,
    p_primary_contact_flag          IN VARCHAR2 DEFAULT 'N',
    P_PERSONAL_FLAG                 IN VARCHAR2 DEFAULT 'N',
    p_use_primary_address           IN VARCHAR2 DEFAULT 'Y',
    p_effective_date                IN  DATE DEFAULT SYSDATE,
    p_primary_flag                  IN  VARCHAR2 DEFAULT 'N',
    p_address_type                  IN  VARCHAR2 DEFAULT NULL,
    p_town_or_city                  IN  VARCHAR2 DEFAULT NULL,
    p_region_1                      IN  VARCHAR2 DEFAULT NULL,
    p_region_2                      IN  VARCHAR2 DEFAULT NULL,
    p_region_3                      IN  VARCHAR2 DEFAULT NULL,
    p_postal_code                   IN  VARCHAR2 DEFAULT NULL,
    p_country                       IN  VARCHAR2 DEFAULT NULL,
    p_add_information13             IN  VARCHAR2 DEFAULT NULL,
    p_add_information14             IN  VARCHAR2 DEFAULT NULL
) RETURN CLOB;

FUNCTION update_sa_contact_person (
    p_person_id                     NUMBER DEFAULT NULL,
    p_validate                      IN  VARCHAR2 DEFAULT 'TRUE',
    p_addEmergency_flag             IN  VARCHAR2 DEFAULT 'N',
    p_contact_person_id             IN  NUMBER,
    p_start_date                    IN  DATE DEFAULT SYSDATE,
    p_family_name                   IN  VARCHAR2,
    p_sex                           IN  VARCHAR2,
    p_person_type_id                IN  NUMBER DEFAULT NULL,
    p_comments                      IN  VARCHAR2 DEFAULT NULL,
    p_date_employee_data_verified   IN  DATE DEFAULT NULL,
    p_date_of_birth                 IN  DATE DEFAULT NULL,
    p_email_address                 IN  VARCHAR2 DEFAULT NULL,
    p_expense_check_send_to_addres  IN  VARCHAR2 DEFAULT NULL,
    p_first_name                    IN  VARCHAR2 DEFAULT NULL,
    p_known_as                      IN  VARCHAR2 DEFAULT NULL,
    p_marital_status                IN  VARCHAR2 DEFAULT NULL,
    p_nationality                   IN  VARCHAR2 DEFAULT NULL,
    p_national_identifier           IN  VARCHAR2 DEFAULT NULL,
    p_previous_last_name            IN  VARCHAR2 DEFAULT NULL,
    p_registered_disabled_flag      IN  VARCHAR2 DEFAULT NULL,
    p_title                         IN  VARCHAR2 DEFAULT NULL,
    p_vendor_id                     IN  NUMBER DEFAULT NULL,
    p_work_telephone                IN  VARCHAR2 DEFAULT NULL,
    p_attribute_category            IN  VARCHAR2 DEFAULT NULL,
    p_father_name                   IN  VARCHAR2 DEFAULT NULL,
    p_grandfather_name              IN  VARCHAR2 DEFAULT NULL,
    p_alt_first_name                IN  VARCHAR2 DEFAULT NULL,
    p_alt_father_name               IN  VARCHAR2 DEFAULT NULL,
    p_alt_grandfather_name          IN  VARCHAR2 DEFAULT NULL,
    p_alt_family_name               IN  VARCHAR2 DEFAULT NULL,
    p_religion                      IN  VARCHAR2 DEFAULT NULL,
    p_hijrah_birth_date             IN  VARCHAR2 DEFAULT NULL,
    p_education_level               IN  VARCHAR2 DEFAULT NULL,
    p_correspondence_language       IN  VARCHAR2 DEFAULT NULL,
    p_honors                        IN  VARCHAR2 DEFAULT NULL,
    p_benefit_group_id              IN  NUMBER DEFAULT NULL,
    p_on_military_service           IN  VARCHAR2 DEFAULT NULL,
    p_student_status                IN  VARCHAR2 DEFAULT NULL,
    p_uses_tobacco_flag             IN  VARCHAR2 DEFAULT NULL,
    p_coord_ben_no_cvg_flag         IN  VARCHAR2 DEFAULT NULL,
    p_town_of_birth                 IN  VARCHAR2 DEFAULT NULL,
    p_region_of_birth               IN  VARCHAR2 DEFAULT NULL,
    p_country_of_birth              IN  VARCHAR2 DEFAULT NULL,
    p_global_person_id              IN  VARCHAR2 DEFAULT NULL,
    p_contact_type                  IN VARCHAR2 DEFAULT NULL,
    p_contact_relationship_id       IN NUMBER DEFAULT 1,
    p_primary_contact_flag          IN VARCHAR2 DEFAULT 'N',
    P_PERSONAL_FLAG                 IN VARCHAR2 DEFAULT 'N',
    p_use_primary_address           IN VARCHAR2 DEFAULT 'Y',
    p_address_id                    IN  NUMBER,
    p_effective_date                IN  DATE DEFAULT SYSDATE,
    p_primary_flag                  IN  VARCHAR2 DEFAULT 'N',
    p_address_type                  IN  VARCHAR2 DEFAULT NULL,
    p_town_or_city                  IN  VARCHAR2 DEFAULT NULL,
    p_region_1                      IN  VARCHAR2 DEFAULT NULL,
    p_region_2                      IN  VARCHAR2 DEFAULT NULL,
    p_region_3                      IN  VARCHAR2 DEFAULT NULL,
    p_postal_code                   IN  VARCHAR2 DEFAULT NULL,
    p_country                       IN  VARCHAR2 DEFAULT NULL,
    p_add_information13             IN  VARCHAR2 DEFAULT NULL,
    p_add_information14             IN  VARCHAR2 DEFAULT NULL
) RETURN CLOB;
